### ISSUE TITLE
Tag a release and support composer workflow

### ISSUE THREAD

**Issue by aautar** [RusticiSoftware/SCORMCloud_PHPLibrary#25]
Would love to be able to manage this as a package in my application with composer (https://getcomposer.org/). It's also pretty standard fare at this point when it comes to managing PHP libraries.

**Comment by sawisia** [comment]
It is great idea. Any update on this one?

**Comment by tedwards** [comment]
Hi Guys, 
You should be able to pull down the latest version from composer now. 

https://packagist.org/packages/rustici-software/scorm-cloud
