### ISSUE TITLE
GetRegistrationListResults does not accept after and until params

### ISSUE THREAD

**Issue by sawisia** [RusticiSoftware/SCORMCloud_PHPLibrary#33]
Hello,

I need to use GetRegistrationListResults with after param, but the php library does not allow to pass the param to the method call. I wanted to create a pull request, but I dont have permission to do so.

Also, do you want to create a tag for current composer version?

**Comment by DillGromble** [comment]
Resolved by https://github.com/RusticiSoftware/SCORMCloud_PHPLibrary/pull/34
