### ISSUE TITLE
problem in config

### ISSUE THREAD

**Issue by natebotts** [RusticiSoftware/SCORMCloud_PHPLibrary#8]
I was testing this library out and all generally seemed to work, but was getting the following error: "Creating default object from empty value in /myLibraryPath/samples/config.php on line 35"

Did a little searching and found a fix that suggested adding "$CFG = new stdClass();" after "unset($CFG);" in the config file.

That seemed to fix it for me, but wanted to see if this was causing some other problem and what might be the more appropriate.

**Comment by jasonspick** [comment]
This also worked for me. Not sure what the implications are in other areas yet. Will update when and if I find any.
